node {
    checkout scm
    stage("Build"){
        docker.image('python:2-alpine').inside {
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }

    checkout scm
    stage("Test"){
        try {
            docker.image('qnib/pytest').inside {
                sh 'py.test --junit-xml test-reports/results.xml sources/test_calc.py'
            }
        } finally {
            junit 'test-reports/results.xml'
        }
    }

    checkout scm
    if (currentBuild.currentResult == 'SUCCESS') {
        stage("Deliver"){
            sh 'docker run --rm -v \$(pwd)/sources:/src cdrx/pyinstaller-linux:python2 "pyinstaller -F add2vals.py"'
            archiveArtifacts 'sources/dist/add2vals'
        }
    }
}